"""
Performance Reporter - Generates comprehensive performance reports for sandbox simulation.
Creates markdown reports with charts and analysis.
"""

import os
from datetime import datetime
from typing import List, Dict
from sandbox.models import PerformanceMetrics, VirtualTrade, EquityPoint


class PerformanceReporter:
    """Generates comprehensive performance reports for sandbox simulation."""

    def __init__(self, output_path: str = "./sandbox_results"):
        self.output_path = output_path

    def generate_report(
        self,
        metrics: PerformanceMetrics,
        trades: List[VirtualTrade],
        equity_curve: List[EquityPoint]
    ) -> str:
        """Generate HTML/PDF performance report."""
        report = f"""# Sandbox Simulation Report

**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
**Simulation Period:** {metrics.start_date.strftime('%Y-%m-%d')} to {metrics.end_date.strftime('%Y-%m-%d')}
**Duration:** {metrics.trading_days} days

---

## 1. Executive Summary

| Metric | Value |
|--------|-------|
| Starting Balance | ${metrics.starting_balance:,.2f} |
| Ending Balance | ${metrics.ending_balance:,.2f} |
| **Total P&L** | **${metrics.total_pnl:,.2f} ({metrics.total_pnl_pct:.2%})** |
| Annualized Return | {metrics.annualized_return:.2%} |
| Win Rate | {metrics.win_rate:.2%} |
| Profit Factor | {metrics.profit_factor:.2f} |
| Sharpe Ratio | {metrics.sharpe_ratio:.2f} |
| Max Drawdown | {metrics.max_drawdown:.2%} |

---

## 2. Performance Overview

### Equity Curve

```
{self._generate_equity_chart(equity_curve)}
```

### Monthly Returns

| Month | Return |
|-------|--------|
{self._generate_monthly_returns_table(metrics, trades)}

---

## 3. Risk Analysis

| Metric | Value | Assessment |
|--------|-------|------------|
| Volatility | {metrics.volatility:.2%} | {"High" if metrics.volatility > 0.05 else "Medium" if metrics.volatility > 0.02 else "Low"} |
| Sharpe Ratio | {metrics.sharpe_ratio:.2f} | {"Excellent" if metrics.sharpe_ratio > 2 else "Good" if metrics.sharpe_ratio > 1 else "Fair" if metrics.sharpe_ratio > 0.5 else "Poor"} |
| Sortino Ratio | {metrics.sortino_ratio:.2f} | {"Excellent" if metrics.sortino_ratio > 3 else "Good" if metrics.sortino_ratio > 2 else "Fair" if metrics.sortino_ratio > 1 else "Poor"} |
| Max Drawdown | {metrics.max_drawdown:.2%} | {"Severe" if metrics.max_drawdown > 0.3 else "Moderate" if metrics.max_drawdown > 0.15 else "Acceptable"} |
| Calmar Ratio | {metrics.calmar_ratio:.2f} | {"Excellent" if metrics.calmar_ratio > 3 else "Good" if metrics.calmar_ratio > 1 else "Fair" if metrics.calmar_ratio > 0.5 else "Poor"} |

---

## 4. Trade Analysis

| Metric | Value |
|--------|-------|
| Total Trades | {metrics.total_trades} |
| Winning Trades | {metrics.winning_trades} |
| Losing Trades | {metrics.losing_trades} |
| Average Win | ${metrics.avg_win:,.2f} |
| Average Loss | ${metrics.avg_loss:,.2f} |
| Win/Loss Ratio | {metrics.win_loss_ratio:.2f} |
| Average Position Size | ${metrics.avg_position_size:,.2f} |
| Maximum Position Size | ${metrics.max_position_size:,.2f} |
| Average Hold Time | {metrics.avg_hold_time_hours:.1f} hours |

---

## 5. Trader Copy Performance

| Metric | Value |
|--------|-------|
| Traders Copied | {metrics.traders_copied} |
| Profitable Traders | {metrics.profitable_traders} |
| Success Rate | {metrics.profitable_traders/metrics.traders_copied:.2%} if metrics.traders_copied > 0 else 0 |

**Top Performer:** {metrics.top_performing_trader}
**Worst Performer:** {metrics.worst_performing_trader}

### Individual Trader Returns

| Trader | Return | Trades | Win Rate |
|--------|--------|--------|----------|
{self._generate_trader_table(metrics)}

---

## 6. Execution Quality

| Metric | Value |
|--------|-------|
| Average Slippage | {metrics.avg_slippage:.4f} |
| Total Fees Paid | ${metrics.total_fees_paid:,.2f} |
| Fill Rate | {metrics.fill_rate:.2%} |
| Partial Fill Rate | {metrics.partial_fill_rate:.2%} |

---

## 7. Recommendations

{self._generate_recommendations(metrics)}

---

*Report generated by CopyCat Sandbox Simulation Engine*
"""
        return report

    def save_report(self, report: str, filename: str = None) -> str:
        """Save report to file."""
        if filename is None:
            timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
            filename = f"sandbox_report_{timestamp}.md"

        filepath = os.path.join(self.output_path, filename)
        os.makedirs(self.output_path, exist_ok=True)

        with open(filepath, 'w') as f:
            f.write(report)

        return filepath

    def _generate_equity_chart(self, equity_curve: List[EquityPoint]) -> str:
        """Generate ASCII equity chart."""
        if len(equity_curve) < 2:
            return "Insufficient data for equity chart"

        values = [point.value for point in equity_curve]
        min_val = min(values)
        max_val = max(values)

        if max_val == min_val:
            return "Constant portfolio value"

        # Normalize to 50 characters
        normalized = [(v - min_val) / (max_val - min_val) * 49 for v in values]
        chart_lines = []

        for i, val in enumerate(normalized):
            bar = '█' * int(val) + '░' * (49 - int(val))
            date_str = equity_curve[i].timestamp.strftime('%m/%d')
            chart_lines.append(f"{date_str} |{bar}| ${values[i]:,.0f}")

        return '\n'.join(chart_lines)

    def _generate_monthly_returns_table(self, metrics: PerformanceMetrics, trades: List[VirtualTrade]) -> str:
        """Generate monthly returns table."""
        return "| Month | Return |\n|-------|--------|\n| Data not available | - |"

    def _generate_trader_table(self, metrics: PerformanceMetrics) -> str:
        """Generate trader performance table."""
        if not metrics.trader_specific_returns:
            return "| No traders copied | $0.00 | 0 | 0% |"

        rows = []
        for trader, pnl in metrics.trader_specific_returns.items():
            rows.append(f"| {trader[:8]}... | ${pnl:,.2f} | - | - |")

        return '\n'.join(rows)

    def _generate_recommendations(self, metrics: PerformanceMetrics) -> str:
        """Generate recommendations based on performance."""
        recommendations = []

        if metrics.sharpe_ratio < 1:
            recommendations.append("- Sharpe ratio below 1.0 suggests inconsistent risk-adjusted returns.")

        if metrics.max_drawdown > 0.2:
            recommendations.append("- Maximum drawdown exceeds 20%. Consider reducing position sizes.")

        if metrics.win_rate < 0.5:
            recommendations.append("- Win rate below 50%. Review trade selection criteria.")

        if metrics.profit_factor < 1.5:
            recommendations.append("- Profit factor below 1.5. Improve risk/reward on trades.")

        if not recommendations:
            recommendations.append("- Performance metrics look good! Consider increasing position sizes.")

        return '\n'.join(recommendations)
